### ISSUE TITLE
Template for directive 'nitAdvancedSearchbox' must have exactly one root element. angular-advanced-searchbox.html

### ISSUE THREAD

**Issue by lidsky** [dnauck/angular-advanced-searchbox#1]
Versions
angular: 1.2.17
angular-advanced-searchbox: ~1.0.0

Any idea?

**Comment by dnauck** [comment]
Hi,

the template only has one root element: https://github.com/dnauck/angular-advanced-searchbox/blob/master/src/angular-advanced-searchbox.html

Where do you get this error?

**Comment by lidsky** [comment]
Yup, your html template looks good. I am suspecting a configuration issue on my part. But this is the full error:

 Error: [$compile:tplrt] Template for directive 'nitAdvancedSearchbox' must have exactly one root element. angular-advanced-searchbox.html
http://errors.angularjs.org/1.2.17/$compile/tplrt?p0=nitAdvancedSearchbox&p1=angular-advanced-searchbox.html
    at http://localhost:9000/dashboard/bower_components/angular/angular.js:78:12
    at http://localhost:9000/dashboard/bower_components/angular/angular.js:6752:21
    at http://localhost:9000/dashboard/bower_components/angular/angular.js:7976:11
    at wrappedCallback (http://localhost:9000/dashboard/bower_components/angular/angular.js:11408:81)
    at wrappedCallback (http://localhost:9000/dashboard/bower_components/angular/angular.js:11408:81)
    at http://localhost:9000/dashboard/bower_components/angular/angular.js:11494:26
    at Scope.$eval (http://localhost:9000/dashboard/bower_components/angular/angular.js:12518:28)
    at Scope.$digest (http://localhost:9000/dashboard/bower_components/angular/angular.js:12330:31)
    at Scope.$apply (http://localhost:9000/dashboard/bower_components/angular/angular.js:12622:24)
    at done (http://localhost:9000/dashboard/bower_components/angular/angular.js:8234:45)


Here is my setup:

1. bower install with save flag
2. Link directive source from bower_components/angular-advanced-searchbox... to index.html
3. Add 'angular-advanced-searchbox' to angular.module('myApp') config
4. put nit-advanced-searchbox directive in a template


Am I missing anything?

Thanks for the cool directive by the way.

**Comment by dnauck** [comment]
Can you verify that the template is not modified in any case? A working sample with all dependencies is in the gh-pages branch.

Maybe just post your example and we can see.

**Comment by dnauck** [comment]
You may want to try version 1.1.0 with embedded template

**Comment by dnauck** [comment]
Looks like this issue is resolved. Please reopen if not.

**Comment by lidsky** [comment]
Yup it is working. I didn't have the right directive template path, hence making the path specified in the directive to be translated into a string template resulting in "one root element error". Thanks a lot.
