### ISSUE TITLE
Load search parameters doesn't clear parameters

### ISSUE THREAD

**Issue by ErikOmberg** [dnauck/angular-advanced-searchbox#10]
I picked up your latest changes from Issue #9 fixes, but I don't think they fixed the issue I was seeing. Here are some screenshots of the search box after I assigned new values to it. This shows the old boxes weren't cleared out. (Example: Author)

![image](https://cloud.githubusercontent.com/assets/8632110/7622408/e571b984-f994-11e4-8744-d81591eedb44.png)

![image](https://cloud.githubusercontent.com/assets/8632110/7622426/01ecab82-f995-11e4-9335-4c5d87620bae.png)

**Comment by dnauck** [comment]
Hm, strange. Could you please step through the code here: https://github.com/dnauck/angular-advanced-searchbox/blob/master/src/angular-advanced-searchbox.js#L55

What does it do in your case?
