### ISSUE TITLE
Suggested values for parameters

### ISSUE THREAD

**Issue by tangokhi** [dnauck/angular-advanced-searchbox#11]
Is it possible to change the component so that it also shows the suggested values for the parameters not only the parameters. So after typing city it shows me the possible values of the city. Just like http://documentcloud.github.io/visualsearch/ . 
Also, I know that an issue has been fixed where when a parameter can only be specified once but in my case I want to specify multiple values for the parameters and at the back-end an "OR" clause will be applied for all the values. How easy is it to do that ?

Thank you

**Comment by dnauck** [comment]
For the second request, please check out #6

**Comment by dnauck** [comment]
So you want auto complete on the values of a search parameter?

We already use the angularjs-ui-bootstrap typeahead directive for that. How do you want so specify the possible values that are shown during autocomplete? How do you want to configure the other options of the typeahead directive for each search parameter?

**Comment by dnordberg** [comment]
Regarding, "We already use the angularjs-ui-bootstrap typeahead directive for that" -> if this is the case, could you update the example to include a usage case?

**Comment by dnordberg** [comment]
+1 on specifying possible values, the api implementation could simply be a function which returns values for the typeahead

**Comment by NealHaggard** [comment]
allow them to either specify allowed values as an array in the parameters defining the search options, or allow a function that returns the array.  If it's not provided, assume it's free text.

**Comment by dnauck** [comment]
Please test the current 2.1 build that is including your requested feature on the master branch.
