### ISSUE TITLE
scope.watch on scope.searchParams stopped working

### ISSUE THREAD

**Issue by ErikOmberg** [dnauck/angular-advanced-searchbox#12]
I had this code working to watch changes on searchParams. It was working with previous versions of angular-advanced-searchbox. My code was receiving a call when searchParams changed by user actions. Then, my code would call a Url to show some search result samples.

![image](https://cloud.githubusercontent.com/assets/8632110/7728902/63d78884-fed7-11e4-89df-71da1941b0e3.png)

This stopped working with the latest angular-advanced-searchbox js file. Is that a bug, or is there a new way to accomplish watching the searchParams changes?
Thank you.

**Comment by hendrix85** [comment]
UPDATE template too ---- angular-advanced-searchbox.html-----

**Comment by dnauck** [comment]
@ErikOmberg normally not, i'm using this new version in a internal project without any problems. Maybe you can debug it a bit in your case?

**Comment by ErikOmberg** [comment]
Yes, it must have been that I needed the angular-advanced-searchbox.html update too.

Sorry for the false alarm. I really like the angular-advanced-searchbox. Thank you!

**Comment by dnauck** [comment]
No problem, thanks for actively reporting issues ;)

**Comment by ErikOmberg** [comment]
Just a follow up:

The thing that seems to be working best for me is to put a watch on searchParams.query and other sub-items of searchParams like this:

    $scope.$watch('searchParams.query', function () {
        console.log('watch searchParams.query changed');
        $scope.searchParamsChanged(false);
    });
    $scope.$watch('searchParams.author', function () {
        console.log('watch searchParams.author changed');
        $scope.searchParamsChanged(false);
    });
    $scope.$watch('searchParams.extension', function () {
        console.log('watch searchParams.extension changed');
        $scope.searchParamsChanged(false);
    });

**Comment by dnauck** [comment]
If you want only one watch, just use a deep object watch, e.g.:

```js
$scope.$watch('model', function (newValue, oldValue) {
// ...
}, true); // deep object watch
```
