### ISSUE TITLE
What is the format for 'parameters'

### ISSUE THREAD

**Issue by estvmachine** [dnauck/angular-advanced-searchbox#13]
Im trying this but dont show like the example.

In the controller
```javascript
  $searchParams= ["value", "id"];
```

In my view
```html
<nit-advanced-searchbox
    ng-model="searchModel"
    parameters="searchParams"
    placeholder="Search...">
</nit-advanced-searchbox>
```

I got this

![image](https://cloud.githubusercontent.com/assets/2062668/7947196/9c54a29c-0949-11e5-9c5c-350aafc3e235.png)

**Comment by hendrix85** [comment]
availableSearchParams: [
            { key: "MMM", name: "ZZZ", placeholder: "VVV... "},
 { key: "MMM1", name: "ZZZ1", placeholder: "VVV1... "},
        ]

**Comment by dnauck** [comment]
@hendrix85 is right, please take a look at the demo page:

Parameter declaration in controller:
https://github.com/dnauck/angular-advanced-searchbox/blob/gh-pages/index.html#L33

Directive declaration:
https://github.com/dnauck/angular-advanced-searchbox/blob/gh-pages/index.html#L80

**Comment by estvmachine** [comment]
Thanks!
