### ISSUE TITLE
Problem with last angular-advanced-searchbox.html template

### ISSUE THREAD

**Issue by dami1c** [dnauck/angular-advanced-searchbox#14]
Hello,

I intalled the last version (1.1.1) with bower. but this one don't work correctly like your demo (1.0.0). The problem is when I clic in the middle of the search component, the component don't take the focus. I found the difference, you have change the template angular-advanced-searchbox.html between the two versions. More precisely, you have remove *ng-click=\"!focus ? setSearchFocus = true : null\"*
Are there a reason? Can you generate a new version with correction?

If I want override this template, what is the best practice?
I wanted add this line in a personal .js file, is it good? : 
    
    angular.module('angular-advanced-searchbox').run(['$templateCache', function($templateCache) {
	  'use strict';
	  $templateCache.put('angular-advanced-searchbox.html',
	    "<div class=advancedSearchBox ......</div>"
	  );
	}]);

Thank you

**Comment by dnauck** [comment]
The problem was that Firefox had problems with the focus.

As soon as you clicked on a parameter suggestion the focus was lost and set again -> the click on the parameter suggestion was lost.

**Comment by dnauck** [comment]
Refs #3

**Comment by dnauck** [comment]
I reverted the change from #3 and tested on the Demo page with Chrome, Firefox and IE 11. Looks like this issue is gone with a newer angularjs.

**Comment by igorlino** [comment]
Any change to make a release with all latest corrections ?
