### ISSUE TITLE
IPad Air 2 IOs 9.1 search text not inside search concept

### ISSUE THREAD

**Issue by wymmeroo** [dnauck/angular-advanced-searchbox#25]
Hi
First of all i love your search concept, its one of the best i ever saw. I validated your control for my project and for this it is necessary that it's running on tablets. In Ios 9.1 in safari, the search text is outside of the "search concept", see screenshot. If we can fix it, I definitely integration your control in my project.

Cheers 
Tobias

![image1](https://cloud.githubusercontent.com/assets/13727378/11359859/354fb90e-9280-11e5-86dd-573e1e27c897.JPG)

**Comment by dnauck** [comment]
That is a correct behavior.

The Search Box has 2 modes:

- Search by parameter
- Search as free text (the query property) -> the one you're seeing in your screen shot

**Comment by dnauck** [comment]
I'll close this now. Let mw know if it is still unclear and reopen that issue if you like.
