### ISSUE TITLE
feature: update to ui-bootstrap 0.14.x

### ISSUE THREAD

**Issue by igorlino** [dnauck/angular-advanced-searchbox#26]
Hi I had a problem since the anagular-advance-searchbox is referencing a pretty old version of angulat-bootstrap, which is anyway not referencing the official bower repository  (https://github.com/angular-ui/bootstrap-bower)

Instead of using the dependency "angular-bootstrap" it should be using angular-ui-bootstrap-bower"

**Comment by dnauck** [comment]
Hi, it is using the correct repository, see here: https://github.com/angular-ui/bootstrap#install-with-bower

And yes i'll update to a newer version.

**Comment by igorlino** [comment]
yeah you are right, now I know the reason: http://stackoverflow.com/a/22180864/4604872

I created the original project in January 2015 (at that time angular-ui-bootstrap-bower was the right dependency) , but Feb 2015 they did changes and some fix, and now its possible to use it like you mentioned.

**Comment by dnauck** [comment]
Can we close this issue then? Currently i'm using a pre 0.14 version because they renamed all directives with a uib- prefix.

I think i'll update to 0.14+ in the beginning of the next year.

**Comment by igorlino** [comment]
Lets just rename it ;)

**Comment by igorlino** [comment]
+1
