### ISSUE TITLE
Enter Edit Mode on mouse click

### ISSUE THREAD

**Issue by peterpuzos** [dnauck/angular-advanced-searchbox#3]
Mouse click on a search parameter to edit the value doesn't seem to be working for me in Firefox or Chrome.  It does set editMode to "true" but also seems to blur or lose focus right away.

**Comment by dnauck** [comment]
Hi,

please try to remove the ```ng-click="!focus ? setSearchFocus = true : null"``` from the first line of the template as temp. workaround.

**Comment by peterpuzos** [comment]
Awesome thanks, that worked.  Didn't think to look at the top line for some reason.

**Comment by dnauck** [comment]
Fixed in Version 1.1.0
