### ISSUE TITLE
Removing a search param does not give any (event) notification

### ISSUE THREAD

**Issue by fizerkhan** [dnauck/angular-advanced-searchbox#32]
We have a submit button to do the search. After a search, when a user removes a particular `search param` by using the trash button, I do not get any noficiation. So if the user does not click the search button again, the user will have a impression that now the filter is removed, but in reality the filter is still present but in the UI the filter is removed. 

It would be very helpful if we can get notification when a search param is removed

**Comment by dnauck** [comment]
So we need new events for removing search params?

Isn't it easier to watch the ng-model object?

**Comment by fizerkhan** [comment]
@dnauck `ng-model` watch is called too many times i guess. It is very nice if you provide event for `remove` and `remove all`.

**Comment by sundarv85** [comment]
+1 We are affected by this. It would be good, if this is fixed.

**Comment by dnauck** [comment]
Ok, added it to my todo list.
