### ISSUE TITLE
Listing possible values

### ISSUE THREAD

**Issue by fizerkhan** [dnauck/angular-advanced-searchbox#33]
When a search param is selected, the list of data is shown only when I start typing. Would it also be possible to list everything when nothing is keyed in.

**Comment by dnauck** [comment]
Your talking about the new autocomplete feature of the unreleased version 2.1?

If the angular-ui-bootstrap directive supports this behavior we can enable it. Otherwise we need to fix this first.

**Comment by fizerkhan** [comment]
@dnauck The autocomplete feature is good. But i want to list everything when nothing is keyed(when first mouse click is happened). Currently, the list of data is shown only when I start typing.

**Comment by twoblokeswithapostie** [comment]
@fizerkhan have you managed to find an answer to this? I need this feature too. I want the search parameter with "suggestedValues" to behave like a dropdown. So when you click on it it displays all the values immediately instead of autocompletion.

**Comment by twoblokeswithapostie** [comment]
He, I think it needs to be done with typeahead-min-length="0", but for some reason the dropdown flashes and disappears... Still investigating why.

**Comment by dnauck** [comment]
Maybe the is fixed by #36 in a future release

**Comment by fizerkhan** [comment]
`typeahead-min-length="0"` is not working for me. Any idea?

**Comment by fizerkhan** [comment]
For me also, for some reason the dropdown flashes and disappears. How do we fix in angular bootstrap 0.13 without moving to 1.0
