### ISSUE TITLE
Search parameters autocompletion not working with Angular Bootstrap 1.x

### ISSUE THREAD

**Issue by jarandaf** [dnauck/angular-advanced-searchbox#36]
Only tested it with `angular-bootstrap~1.0.0` and the autocompletion feature stopped working. Rolling back to `angular-bootstrap#0.13.0` did the trick.

**Comment by dnauck** [comment]
Yes, see #26 

I'll try to port my own application as soon as possible to the latest angular-ui-bootstrap so we can solve #26 and #36.

As a workaround you can rename the bootstrap directives yourself in the template with a custom build.
They renamed everything with a prefix in version 0.14. (There is a wiki page about that breaking change)

**Comment by pc660** [comment]
Do you have plans about when this will be completed?
I really like this component but I can't use it because of this issue. :)

**Comment by dnauck** [comment]
It is planned to implemented during the next 4-5 weeks.
