### ISSUE TITLE
search parameter input closes when you click on it

### ISSUE THREAD

**Issue by DarioSacco** [dnauck/angular-advanced-searchbox#38]
The ng-blur on the input with name = "value" fires also when you click onto the word you are typing. I want the input to leave the edit mode only when you click OUT of the input bar

**Comment by dnauck** [comment]
I'm using here the standard ng-blur directive from angular, any idea how we can fix this?

**Comment by Corwynt** [comment]
Should be fixed with:
#40

**Comment by DarioSacco** [comment]
Can you explain what your code does? It doesn't work for me. 
I was thinking, when the blur fires, to check if the e.target.name is "value" and in that case do nothing (because I want to leave the edit mode only on enter key or click elsewhere) but there's something ignoring that check and the search param leaves the edit mode even before it (probably is the $scope.$watch inside the nitSetFocus directive)

**Comment by Corwynt** [comment]
The target element in the Blur event is the Element with the ng-blur directive. In my test case the HTML-Element which caused, that the input element lost its focus was `event.relatedTarget`.
To check if it is an Typeahed element i check if the parent Element's  id attribute includes the word "typeahead".

**Comment by DarioSacco** [comment]
I was not referring to typeahead elements but the search param where you tipe in the values to filter with.
Anyway I fixed it using the check I was talking before: added an if in the watch block like this

```
$scope.$watch(model, function (value) {
                            if (value === true) {
                                $timeout(function () {
                                    **if ($element[0].name === "value" || $element[0].value !== "")**
                                        $element[0].focus();
                                });
                            }
                        });
```

**Comment by dnauck** [comment]
Thanks for you help. I'll try to understand and test your contributions.

**Comment by dnauck** [comment]
Please test my latest commit if this fixes both issues.

**Comment by dnauck** [comment]
Closing this now, please reopen if issue is still present
