### ISSUE TITLE
JSPM Install

### ISSUE THREAD

**Issue by amcdnl** [dnauck/angular-advanced-searchbox#4]
When I do a JSPM install I'm getting: http://www.screencast.com/t/S0FO6p3S

Its complaining that there is no main entry point detected.  I noticed in your main its pointing to the src file too instead of the dist.  I think most things point at dist file but i could be wrong.

**Comment by dnauck** [comment]
Hi,

thanks for using my project ;)

I don't know JSPM, but what does it expect as "main" ?
I'm happy to fix it or accept a pull request to make your life easier.

**Comment by amcdnl** [comment]
Heres some info on JSPM:

- http://javascriptplayground.com/blog/2014/11/js-modules-jspm-systemjs/
- http://glenmaddern.com/articles/javascript-in-2015

Lots of people are positioning it as the next bower.

**Comment by dnauck** [comment]
For the second issue, please open a new issue. Thank you very much.
