### ISSUE TITLE
Advanced Search Box with Flask

### ISSUE THREAD

**Issue by kns94** [dnauck/angular-advanced-searchbox#44]
Hi, I am using Flask in the backend and would like to use Advanced Search box. Could you please state dependencies? A tutorial would also help!

**Comment by dnauck** [comment]
Hi, what is Flask? The searchbox does not have any server side dependencies.

Checkout the gh-pages branch for a complete example.

**Comment by kns94** [comment]
Yes, But I am not using bower or nodejs, so am getting errors to compile.

**Comment by dnauck** [comment]
Why do you want to compile (what?)?

Just include the required java script and css files like the demo in the gh-pages branch.

There is no dependency on npm or bower (they're just my own development dependencies)

**Comment by kns94** [comment]
let me try once again

**Comment by dnauck** [comment]
Closing this for now, please reopen if you still have issues.
