### ISSUE TITLE
Long query string only shows partial text

### ISSUE THREAD

**Issue by ErikOmberg** [dnauck/angular-advanced-searchbox#5]
Long query string only shows partial text:

Is there a way to change this to show the full query string text? Please see the attached screenshot.

Notice the tail of the 'g', 'q', and 'y' characters are cut off in the text box too. If you know how to fix that, that'd be really great too. Thank you!

![image](https://cloud.githubusercontent.com/assets/8632110/6942072/96fe8b6c-d84a-11e4-9290-30071795bdef.png)

**Comment by dnauck** [comment]
Hi,

this has something todo with the max input size of bootstraps css i think.

**Comment by dnauck** [comment]
This line is responsible for the max-width setting:
https://github.com/dnauck/angular-advanced-searchbox/blob/master/src/angular-advanced-searchbox.js#L286

Problem is if you want the full size you need to call ```$element.parent().parent().parent().innerWidth();``` which is nut useful on other usecases of this directive.

You can override the calculated ```max-width``` by editign the css file and add sth like: ```max-width: 100%;``` but this will make your UI ugly on very long input texts.

The css line is here:
https://github.com/dnauck/angular-advanced-searchbox/blob/master/src/angular-advanced-searchbox.css#L68

**Comment by ErikOmberg** [comment]
I'm sorry, but I'm confused on your response. I'm probably implementing it wrong, but I was not able to change the behavior. I tried to hard code the maxWidth value to various values, and that didn't have any effect. I tried to edit the CSS with max-width too, but again no effect was observed.

I cleared my browser cache to make sure that wasn't the problem too.

![image](https://cloud.githubusercontent.com/assets/8632110/7598907/78291d12-f8c3-11e4-9bd3-b2bb71612d14.png)

**Comment by dnauck** [comment]
Hi @ErikOmberg i was talking about search parameter's size, not the size of the search box itself.

Searchbox size was fixed in 910358d

**Comment by ErikOmberg** [comment]
Ok, got it fixed up. As you suggested, the CSS fixed the "q tail" issue. This worked well for me:

    .advancedSearchBox .search-parameter-input {
        display: inline-block;
        width: 100%;
        height: 28px;
        border: 0;
        margin: 0;
        padding: 0;
    }


I also made this change in the js file. When I would "load a search" the first time, the displayed query was being truncated. I think I tracked that down to where the placeholder's width was being calculated and set in this section of code:

                        function resize() {
                            shadow.text($element.val() || $element.attr('placeholder'));
                            //$element.css('width', shadow.outerWidth() + 10);
                            $element.css('width', '600px');
                        }

Closing this issue. Thank you.
