### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by harishr2222** [dnauck/angular-advanced-searchbox#51]
is there a npm module for this angular-advanced-searchbox?

regards
harish

**Comment by dnauck** [comment]
Hi,

i had everything prepared, but not published it.

You can find it now at https://www.npmjs.com/package/angular-advanced-searchbox

**Comment by harishr2222** [comment]
Hi,

do you have any idea like when are you planning to publish it?

Regards,
Harish

**Comment by dnauck** [comment]
What kind of error?

**Comment by harishr2222** [comment]
when i run below command 

npm i angular-advanced-searchbox

getting below errror

6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "angular-advanced-searchbox"

npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! angular-advanced-searchbox@3.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-advanced-searchbox@3.0.0 postinstall script 'bowe
r install'.
npm ERR! This is most likely a problem with the angular-advanced-searchbox packa
ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-advanced-searchbox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-advanced-searchbox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Admin\Desktop\ET-WS\jquery\npm-debug.log

regards,
Harish

**Comment by dnauck** [comment]
Can you install `bower` and try again?

`npm install -g bower`
