### ISSUE TITLE
Extra backspaces cause the browser to navigate back to previous page

### ISSUE THREAD

**Issue by katedobroth** [dnauck/angular-advanced-searchbox#52]
1. Click on a search suggestion.
2. Type a letter in the search field, then backspace to erase it.
3. Type backspace again. The search suggestion field disappears. The larger search box is no longer in focus.
4. Type backspace again. This causes the browser to navigate back to the previous page. This happens to me pretty often.

Is there a way that the larger search field could stay in focus after search parameter fields disappear? This would prevent an extra backspace from navigating to the previous page.

Thank you for making this available.

**Comment by dnauck** [comment]
Ok, also noticed this sometimes. Thanks for this bug report.

**Comment by dnauck** [comment]
Please test the latest build

**Comment by katedobroth** [comment]
It's not working for me. I'm trying to be sure that it's not something that I've done. Have you put the new build on your demo page? I ask because I see the same behavior there. When the outer box is blue, it's focused and extra backspaces are blocked. After a search parameter has been cleared with backspaces, though, the outer box is gray and not focused. Extra backspaces still navigate back.

I'll keep trying to see if it's something that I've done, but I wanted to get back to you. Thanks.

**Comment by dnauck** [comment]
Ah, the Demo page was not updated yesterday, but now. (Clear browser cache)

**Comment by katedobroth** [comment]
I'm still seeing the issue on the demo page, even after clearing my cache. I sent you an email yesterday with a video of my screen. This might explain more clearly what I am seeing.

**Comment by dnauck** [comment]
I updated the build and Demo page, please try again

**Comment by katedobroth** [comment]
Demo looks great!  Thank you!

I'll try it out in my code in the next few days.
