### ISSUE TITLE
Load search parameters from "Saved Search" or pre-built search

### ISSUE THREAD

**Issue by ErikOmberg** [dnauck/angular-advanced-searchbox#7]
My application allow a user to "Save Searches" and then later load them up for editing, export, or whatever.

The save/load part works, and I can set $scope.searchParams. The assignment seems fine. If I display searchParams in the UI, it shows the expected json string:
```{{searchParams | json}}```

The search box doesn't update with the searchParams data that is loaded. Is there a way to make the input search box load up the search parameters that are assigned to $scope.searchParams?

Example "Load Saved Search" function that executes on button click:

    $scope.loadSavedSearch = function () {
        $scope.searchParams = $scope.loadSavedSearchSelected.SearchParameters;
    }

Thank you.

**Comment by dnauck** [comment]
Hi,

this currently only works on the page load (e.g. restore from URL/routeParams, etc.)

I've also the use case to add one ore more params via mouse click after page load.
In my case the ng-model of the directive is right, but the extra added param is not visible.

**Comment by dnauck** [comment]
Added support for adding or changing search parameters via ng-model in 3d58af7
