### ISSUE TITLE
Is this repo/project abandoned?

### ISSUE THREAD

**Issue by marchrius** [dnauck/angular-advanced-searchbox#75]
There are a lot of issues but last commit is on 9 Jun [f16daf5](https://github.com/dnauck/angular-advanced-searchbox/commit/f16daf59a1dc18395b7ef4953c0d4c8aba543e3b).
Is this repository or the entire project abandoned?

**Comment by dnauck** [comment]
Hi,

no its not. I'm using this a lot in a production environment/project.

I hope i'll find some time in the next year to fix the outstanding issues.

**Comment by sundarv85** [comment]
+1

**Comment by sgebhardt** [comment]
I love this control. Please find a little time to check and merge the open pull requests.

**Comment by sgebhardt** [comment]
Is this little project now dead?

**Comment by dnauck** [comment]
I'll fix some oustanding issues and release a new version in the near future

**Comment by Nicolas-Aguila** [comment]
Hola a todos. Alguno intento montarlo en Angular 9/10? Tuvo exito?
