### ISSUE TITLE
Load search parameters doesn't clear parameters

### ISSUE THREAD

**Issue by ErikOmberg** [dnauck/angular-advanced-searchbox#9]
I picked up the updates for Issue #7 that you implemented. They worked, but I may have found a bug:
![image](https://cloud.githubusercontent.com/assets/8632110/7598538/8d001540-f8c0-11e4-81bd-d0b0c91e5e70.png)

If I load a saved search, parameters that aren't in the loaded search don't get cleared out. These screenshots show after I load the "exclude" : "Exclude" search, then the "author" : "Erik" and "query" : "BOOM!" parameters didn't get cleared out.

![image](https://cloud.githubusercontent.com/assets/8632110/7598551/a71e68f0-f8c0-11e4-9b9d-c95047b096ab.png)

**Comment by dnauck** [comment]
Yes, the current implementation of #7 will only add new parameters or change values of existing ones.

**Comment by dnauck** [comment]
Fixed in 5d9063f
